apiVersion: v1
kind: Secret
metadata:
  name: pizzaflow-db-credentials
  namespace: pizzaflow
  labels:
    app.kubernetes.io/part-of: pizzaflow-ecosystem
type: Opaque
stringData:
  # PostgreSQL
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  
  # MongoDB
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin"
  
  # Redis (if authentication enabled)
  REDIS_PASSWORD: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: pizzaflow-keycloak-credentials
  namespace: pizzaflow
  labels:
    app.kubernetes.io/part-of: pizzaflow-ecosystem
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: pizzaflow-mail-credentials
  namespace: pizzaflow
  labels:
    app.kubernetes.io/part-of: pizzaflow-ecosystem
type: Opaque
stringData:
  MAIL_USERNAME: "noreply@pizzaflow.com"
  MAIL_PASSWORD: ""
