apiVersion: v1
kind: ConfigMap
metadata:
  name: pizzaflow-common-config
  namespace: pizzaflow
  labels:
    app.kubernetes.io/part-of: pizzaflow-ecosystem
data:
  # Spring profiles
  SPRING_PROFILES_ACTIVE: "kubernetes"
  
  # Eureka Discovery
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-service:8761/eureka/"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  
  # Kafka
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  
  # Redis
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  
  # Management endpoints
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  
  # Tracing
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "0.1"
