FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
RUN addgroup -S pizzaflow && adduser -S pizzaflow -G pizzaflow && mkdir -p /tmp/pizzaflow-logs && chown -R pizzaflow:pizzaflow /app /tmp/pizzaflow-logs
COPY --chown=pizzaflow:pizzaflow services/api-gateway/target/*.jar app.jar
ENV LOG_PATH="/tmp/pizzaflow-logs"
ENV JAVA_OPTS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseZGC"
USER pizzaflow
EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]

