/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as MenuIndexRouteImport } from './routes/menu/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as KitchenIndexRouteImport } from './routes/kitchen/index'
import { Route as CourierIndexRouteImport } from './routes/courier/index'
import { Route as BookingsIndexRouteImport } from './routes/bookings/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders/$orderId'
import { Route as MenuItemIdRouteImport } from './routes/menu/$itemId'
import { Route as ManagerMenuRouteImport } from './routes/manager/menu'
import { Route as ManagerInventoryRouteImport } from './routes/manager/inventory'
import { Route as ManagerBookingsRouteImport } from './routes/manager/bookings'
import { Route as ManagerAnalyticsRouteImport } from './routes/manager/analytics'
import { Route as KitchenHistoryRouteImport } from './routes/kitchen/history'
import { Route as CourierHistoryRouteImport } from './routes/courier/history'
import { Route as BookingsNewRouteImport } from './routes/bookings/new'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAlertsRouteImport } from './routes/admin/alerts'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenIndexRoute = KitchenIndexRouteImport.update({
  id: '/kitchen/',
  path: '/kitchen/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierIndexRoute = CourierIndexRouteImport.update({
  id: '/courier/',
  path: '/courier/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuItemIdRoute = MenuItemIdRouteImport.update({
  id: '/menu/$itemId',
  path: '/menu/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerMenuRoute = ManagerMenuRouteImport.update({
  id: '/manager/menu',
  path: '/manager/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerInventoryRoute = ManagerInventoryRouteImport.update({
  id: '/manager/inventory',
  path: '/manager/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerBookingsRoute = ManagerBookingsRouteImport.update({
  id: '/manager/bookings',
  path: '/manager/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerAnalyticsRoute = ManagerAnalyticsRouteImport.update({
  id: '/manager/analytics',
  path: '/manager/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenHistoryRoute = KitchenHistoryRouteImport.update({
  id: '/kitchen/history',
  path: '/kitchen/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CourierHistoryRoute = CourierHistoryRouteImport.update({
  id: '/courier/history',
  path: '/courier/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsNewRoute = BookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/admin/services',
  path: '/admin/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/admin/alerts',
  path: '/admin/alerts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/callback': typeof CallbackRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/services': typeof AdminServicesRoute
  '/bookings/new': typeof BookingsNewRoute
  '/courier/history': typeof CourierHistoryRoute
  '/kitchen/history': typeof KitchenHistoryRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/bookings': typeof ManagerBookingsRoute
  '/manager/inventory': typeof ManagerInventoryRoute
  '/manager/menu': typeof ManagerMenuRoute
  '/menu/$itemId': typeof MenuItemIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/courier/': typeof CourierIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/callback': typeof CallbackRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/services': typeof AdminServicesRoute
  '/bookings/new': typeof BookingsNewRoute
  '/courier/history': typeof CourierHistoryRoute
  '/kitchen/history': typeof KitchenHistoryRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/bookings': typeof ManagerBookingsRoute
  '/manager/inventory': typeof ManagerInventoryRoute
  '/manager/menu': typeof ManagerMenuRoute
  '/menu/$itemId': typeof MenuItemIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/courier': typeof CourierIndexRoute
  '/kitchen': typeof KitchenIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/menu': typeof MenuIndexRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/callback': typeof CallbackRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/services': typeof AdminServicesRoute
  '/bookings/new': typeof BookingsNewRoute
  '/courier/history': typeof CourierHistoryRoute
  '/kitchen/history': typeof KitchenHistoryRoute
  '/manager/analytics': typeof ManagerAnalyticsRoute
  '/manager/bookings': typeof ManagerBookingsRoute
  '/manager/inventory': typeof ManagerInventoryRoute
  '/manager/menu': typeof ManagerMenuRoute
  '/menu/$itemId': typeof MenuItemIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/courier/': typeof CourierIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/menu/': typeof MenuIndexRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/callback'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/notifications'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/services'
    | '/bookings/new'
    | '/courier/history'
    | '/kitchen/history'
    | '/manager/analytics'
    | '/manager/bookings'
    | '/manager/inventory'
    | '/manager/menu'
    | '/menu/$itemId'
    | '/orders/$orderId'
    | '/admin/'
    | '/bookings/'
    | '/courier/'
    | '/kitchen/'
    | '/manager/'
    | '/menu/'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/callback'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/notifications'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/services'
    | '/bookings/new'
    | '/courier/history'
    | '/kitchen/history'
    | '/manager/analytics'
    | '/manager/bookings'
    | '/manager/inventory'
    | '/manager/menu'
    | '/menu/$itemId'
    | '/orders/$orderId'
    | '/admin'
    | '/bookings'
    | '/courier'
    | '/kitchen'
    | '/manager'
    | '/menu'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/callback'
    | '/cart'
    | '/checkout'
    | '/login'
    | '/notifications'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/services'
    | '/bookings/new'
    | '/courier/history'
    | '/kitchen/history'
    | '/manager/analytics'
    | '/manager/bookings'
    | '/manager/inventory'
    | '/manager/menu'
    | '/menu/$itemId'
    | '/orders/$orderId'
    | '/admin/'
    | '/bookings/'
    | '/courier/'
    | '/kitchen/'
    | '/manager/'
    | '/menu/'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CallbackRoute: typeof CallbackRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminServicesRoute: typeof AdminServicesRoute
  BookingsNewRoute: typeof BookingsNewRoute
  CourierHistoryRoute: typeof CourierHistoryRoute
  KitchenHistoryRoute: typeof KitchenHistoryRoute
  ManagerAnalyticsRoute: typeof ManagerAnalyticsRoute
  ManagerBookingsRoute: typeof ManagerBookingsRoute
  ManagerInventoryRoute: typeof ManagerInventoryRoute
  ManagerMenuRoute: typeof ManagerMenuRoute
  MenuItemIdRoute: typeof MenuItemIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  CourierIndexRoute: typeof CourierIndexRoute
  KitchenIndexRoute: typeof KitchenIndexRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
  MenuIndexRoute: typeof MenuIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/': {
      id: '/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen/': {
      id: '/kitchen/'
      path: '/kitchen'
      fullPath: '/kitchen/'
      preLoaderRoute: typeof KitchenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier/': {
      id: '/courier/'
      path: '/courier'
      fullPath: '/courier/'
      preLoaderRoute: typeof CourierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$itemId': {
      id: '/menu/$itemId'
      path: '/menu/$itemId'
      fullPath: '/menu/$itemId'
      preLoaderRoute: typeof MenuItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/menu': {
      id: '/manager/menu'
      path: '/manager/menu'
      fullPath: '/manager/menu'
      preLoaderRoute: typeof ManagerMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/inventory': {
      id: '/manager/inventory'
      path: '/manager/inventory'
      fullPath: '/manager/inventory'
      preLoaderRoute: typeof ManagerInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/bookings': {
      id: '/manager/bookings'
      path: '/manager/bookings'
      fullPath: '/manager/bookings'
      preLoaderRoute: typeof ManagerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/analytics': {
      id: '/manager/analytics'
      path: '/manager/analytics'
      fullPath: '/manager/analytics'
      preLoaderRoute: typeof ManagerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen/history': {
      id: '/kitchen/history'
      path: '/kitchen/history'
      fullPath: '/kitchen/history'
      preLoaderRoute: typeof KitchenHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courier/history': {
      id: '/courier/history'
      path: '/courier/history'
      fullPath: '/courier/history'
      preLoaderRoute: typeof CourierHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/new': {
      id: '/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof BookingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/admin/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/admin/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CallbackRoute: CallbackRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminServicesRoute: AdminServicesRoute,
  BookingsNewRoute: BookingsNewRoute,
  CourierHistoryRoute: CourierHistoryRoute,
  KitchenHistoryRoute: KitchenHistoryRoute,
  ManagerAnalyticsRoute: ManagerAnalyticsRoute,
  ManagerBookingsRoute: ManagerBookingsRoute,
  ManagerInventoryRoute: ManagerInventoryRoute,
  ManagerMenuRoute: ManagerMenuRoute,
  MenuItemIdRoute: MenuItemIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  CourierIndexRoute: CourierIndexRoute,
  KitchenIndexRoute: KitchenIndexRoute,
  ManagerIndexRoute: ManagerIndexRoute,
  MenuIndexRoute: MenuIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
