{{- if .Values.configService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pizzaflow.fullname" . }}-config-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "pizzaflow.labels" . | nindent 4 }}
    app: config-service
    app.kubernetes.io/component: platform
spec:
  replicas: {{ .Values.configService.replicaCount }}
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
        {{- include "pizzaflow.selectorLabels" . | nindent 8 }}
      annotations:
        {{- include "pizzaflow.prometheusAnnotations" (dict "port" .Values.configService.service.port) | nindent 8 }}
    spec:
      {{- include "pizzaflow.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: config-service
          image: "{{ .Values.global.imageRegistry }}{{ .Values.configService.image.repository }}:{{ .Values.configService.image.tag }}"
          imagePullPolicy: {{ .Values.configService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.configService.service.port }}
          env:
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: {{ .Values.configService.git.uri | quote }}
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
              value: {{ .Values.configService.git.branch | quote }}
          resources:
            {{- toYaml .Values.configService.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.configService.service.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.configService.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pizzaflow.fullname" . }}-config-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "pizzaflow.labels" . | nindent 4 }}
    app: config-service
spec:
  type: {{ .Values.configService.service.type }}
  ports:
    - port: {{ .Values.configService.service.port }}
      targetPort: {{ .Values.configService.service.port }}
      protocol: TCP
      name: http
  selector:
    app: config-service
{{- end }}
