apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pizzaflow.fullname" . }}-common-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "pizzaflow.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.global.environment | quote }}
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://{{ include "pizzaflow.fullname" . }}-discovery-service:8761/eureka/"
  SPRING_CLOUD_CONFIG_URI: "http://{{ include "pizzaflow.fullname" . }}-config-service:8888"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "{{ .Release.Name }}-kafka:9092"
  SPRING_DATA_REDIS_HOST: "{{ .Release.Name }}-redis-master"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_MONGODB_HOST: "{{ .Release.Name }}-mongodb"
  SPRING_DATA_MONGODB_PORT: "27017"
  SPRING_DATA_MONGODB_DATABASE: "pizzaflow_catalog"
  POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
  POSTGRES_PORT: "5432"
